name: composite-gemini3d
description: build or cache Gemini3D

runs:

  using: composite

  steps:

  - name: Checkout GemGI (for simulation config.nml inputs)
    uses: actions/checkout@v6
    with:
      repository: gemini3d/gemci
      path: ${{ github.workspace }}/gemci

  - name: Resolve Gemini3D remote SHA
    id: gemini3d-sha
    shell: bash
    run: |
      echo "sha=$(git ls-remote https://github.com/gemini3d/gemini3d.git HEAD | cut -f1)" >> "$GITHUB_OUTPUT"

  - name: Cache install Gemini3D
    id: cache-gemini
    uses: actions/cache@v5
    with:
      path: ${{ env.CMAKE_INSTALL_PREFIX }}
      key: ${{ runner.os }}-gemini-${{ env.CXX }}-${{ steps.gemini3d-sha.outputs.sha }}

  - name: Checkout Gemini3D
    if: steps.cache-gemini.outputs.cache-hit != 'true'
    uses: actions/checkout@v6
    with:
      repository: gemini3d/gemini3d
      ref: ${{ steps.gemini3d-sha.outputs.sha }}
      path: ${{ github.workspace }}/gemini3d
      submodules: true

  - name: non-cache Install Gemini3D
    if: steps.cache-gemini.outputs.cache-hit != 'true'
    shell: bash
    run: |
      cmake --preset default
      cmake --build build
      cmake --install build
    working-directory: ${{ github.workspace }}/gemini3d
