name: ci

env:
  CMAKE_BUILD_TYPE: Release
  CMAKE_INSTALL_PREFIX: ~/libgem
  GEMINI_ROOT: ~/libgem
  CMAKE_GENERATOR: Ninja
  HOMEBREW_NO_INSTALL_CLEANUP: 1

# GEMINI_ROOT is used to find Gemini3D by PyGemini

on:
  push:
    paths:
    - "**.py"
    - ".github/workflows/**"
    - "src/gemini3d/libraries.json"
    - "!scripts/**"
    - "!example/**"
    - "!Examples/**"
  workflow_dispatch:


jobs:

  core:
    timeout-minutes: 45

    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.11", "3.12", "3.13", "3.14"]
        os: [ubuntu-latest]
        include:
        - os: macos-latest
          python-version: "3.14"

    runs-on: ${{ matrix.os }}

    name: ${{ matrix.os }} Python ${{ matrix.python-version }}

    steps:

    - name: Git Checkout ${{ github.action_repository }}
      uses: actions/checkout@v6

    - name: GCC compiler (macOS)
      if: runner.os == 'macOS'
      run: |
        echo "CC=gcc-15" >> $GITHUB_ENV
        echo "CXX=g++-15" >> $GITHUB_ENV
        echo "FC=gfortran-15" >> $GITHUB_ENV

    - uses: ./.github/workflows/composite-python
      timeout-minutes: 15
      env:
        GEMINI_CIROOT: ${{ github.workspace }}/ci
        GEMCI_ROOT: ${{ github.workspace }}/gemci

    - name: upload test files if failed
      if: failure()
      uses: actions/upload-artifact@v7
      with:
        name: input-${{ runner.os }}-py${{ matrix.python-version }}
        path: ${{ github.workspace }}/pytest/test*mini2*current
        retention-days: 1

    - uses: ./.github/workflows/composite-pkg
      if: runner.os == 'Linux'
      timeout-minutes: 15

    - uses: ./.github/workflows/composite-gemini3d
      if: runner.os == 'Linux'
      timeout-minutes: 15

    - name: Executable tests
      if: runner.os == 'Linux'
      run: pytest ${{ github.workspace }} -m "exe" --basetemp=${{ github.workspace }}/pytest-exe
      env:
        GEMCI_ROOT: ${{ github.workspace }}/gemci
        GEMINI_CIROOT: ${{ github.workspace }}/ci

    - name: upload test files if failed
      if: failure()
      uses: actions/upload-artifact@v7
      with:
        name: exe-${{ runner.os }}-py${{ matrix.python-version }}
        path: ${{ github.workspace }}/pytest-exe/test*mini2*current
        retention-days: 1


# codecov coverage
    # - run: pip install codecov pytest-cov
    # - run: pytest --cov --cov-report=xml
    # - name: Upload coverage to Codecov
    #   uses: codecov/codecov-action@v1
